travis:
  secure:
    BINSTAR_TOKEN: z1R8DMLhOf29TYA83XLfsK2hLPp92h9lhu5UFqqsbL855wcahTxUkxKcoZfwITEqTZsBiMhK/JlrQCWD2NQHe/R9Pz4NsBYOmbLPeYdW0QSu4sP7OgSBkw3ae67DW2rhnR0rxj+wJaIzwCT/j9u5pmhYXlWLMNqw7tipnhh7RxJ+iIapZXpW0/xRUzSq7EmblZeZ5ckTH7JSp33dAQbl7RpvxS0QGVluyaQHGsLhqesvgiijaWJ42ukj6/HDZbQugeUYpcct2KOHy624v+Bs4rbYjAjSKmzP+pLUGLgI6PSrUDoRfUPe0uTiaPZtgwse/NhRnOh7KO7EGlsBjCjmlnzrOp20sOcqkNekzhX0vceVNtLkZarZol5riIdNZ0QyRkuPqyZpGdu+k3oqNx1tQ/Wz6jioPoKraXbUquxPdu/cgKnx1vNiMxYGhK9yHs95YT8ro6VIFvr/2diciZbeUXapvGZEJwPHsYdo6xosjKloudWXiQvGGKGCV1ttdfor+VlCxZmuhB0mcJyWOCSv4LDrglqFTWEgVWGFDxu/gC8CfTdnXzHBlwNxlFWNX2JgROGUVB0BJG1nHC9g8u6mTsGt3V6ngFe9K+LGkrRvU7D6cE60/5JsljWfNDStp/TRMMSLXWi3g4LBwPJlqEB/mak/S2lQ6ZrZ5wonT+nvJas=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
